// This file is regenerated by `vercel build` from server/vercel-handler.ts
// via the esbuild step in vercel.json's buildCommand. The committed content
// is a placeholder so Vercel detects api/index.js as a serverless function
// during pre-build scanning; the real bundle (~90KB) replaces it at deploy.
export default function handler(_req, res) {
  res.statusCode = 500;
  res.setHeader("content-type", "application/json");
  res.end(JSON.stringify({ error: "Function bundle was not built. Check Vercel build logs for esbuild errors." }));
}
